version: '3.8'

services:
  # Academic Apex Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: academic_apex_backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - CURATOR_SERVICE_URL=http://curator:5001
      - OBSIDIAN_VAULT_PATH=${OBSIDIAN_VAULT_PATH:-}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-mistral:7b}
      - UPLOAD_DIR=/app/uploads
      - GENERATED_DIR=/app/generated
    volumes:
      - ./generated:/app/generated
      - ./uploads:/app/uploads
      - ${OBSIDIAN_VAULT_PATH:-./obsidian_vault}:/app/obsidian_vault
    depends_on:
      - curator
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Curator Service for Prompt Optimization
  curator:
    build:
      context: ./backend
      dockerfile: Dockerfile.curator
    container_name: academic_apex_curator
    ports:
      - "5001:5001"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - CURATOR_MODEL=${CURATOR_MODEL:-mistral:7b}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Frontend (Optional - for production builds)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: academic_apex_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: academic_apex_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
    profiles:
      - production

volumes:
  generated_data:
    driver: local
  uploads_data:
    driver: local

networks:
  default:
    name: academic_apex_network
